"""Policy registry + lookup helpers for MCP Server 3.

The policy documents themselves live in data/policies/ (generated by
scripts/generate_policies.py). This module owns the topic -> file mapping, the
metadata each resource advertises, and a small keyword matcher so an agent can
find the right policy from a natural-language question.
"""
from __future__ import annotations

from common.config import POLICY_DOCS_DIR

VERSION = "1.0"
EFFECTIVE_DATE = "2026-01-01"
SOURCE = "Wanderlux Demo Travel (fictional demo issuer)"

# topic -> metadata. `keywords` drive find_policy().
POLICIES: dict[str, dict] = {
    "visa": {
        "filename": "visa_policy.md",
        "policy_name": "Visa Policy (Demo)",
        "category": "entry_requirements",
        "destination": "global",
        "keywords": ["visa", "entry requirement", "e-visa", "visa on arrival",
                     "travel authorisation", "travel authorization", "immigration",
                     "denied entry", "transit visa"],
    },
    "passport": {
        "filename": "passport_policy.md",
        "policy_name": "Passport Requirements Policy (Demo)",
        "category": "entry_requirements",
        "destination": "global",
        "keywords": ["passport", "six month", "six-month", "validity", "blank page",
                     "name match", "dual national", "lost passport"],
    },
    "insurance": {
        "filename": "insurance_policy.md",
        "policy_name": "Travel Insurance Policy (Demo)",
        "category": "protection",
        "destination": "global",
        "keywords": ["insurance", "medical cover", "coverage", "evacuation",
                     "claim", "exclusion", "protection", "premium"],
    },
    "baggage": {
        "filename": "baggage_policy.md",
        "policy_name": "Airline Baggage Policy (Demo)",
        "category": "flights",
        "destination": "global",
        "keywords": ["baggage", "luggage", "bag", "carry-on", "carry on",
                     "cabin bag", "checked bag", "weight limit", "overweight",
                     "lost luggage", "excess baggage"],
    },
    "hotel-cancellation": {
        "filename": "hotel_cancellation_policy.md",
        "policy_name": "Hotel Cancellation Policy (Demo)",
        "category": "accommodation",
        "destination": "global",
        "keywords": ["hotel cancellation", "cancel my hotel", "cancel hotel",
                     "accommodation cancellation", "no-show", "early departure",
                     "free cancellation", "hotel refund"],
    },
    "flight-cancellation": {
        "filename": "flight_cancellation_policy.md",
        "policy_name": "Flight Cancellation Policy (Demo)",
        "category": "flights",
        "destination": "global",
        "keywords": ["flight cancellation", "cancel my flight", "cancel flight",
                     "schedule change", "delay compensation", "missed connection",
                     "denied boarding", "flight refund"],
    },
    "refund": {
        "filename": "refund_policy.md",
        "policy_name": "Refund Policy (Demo)",
        "category": "payments",
        "destination": "global",
        "keywords": ["refund", "money back", "travel credit", "chargeback",
                     "processing time", "non-refundable", "reimbursement"],
    },
    "transportation": {
        "filename": "transportation_policy.md",
        "policy_name": "Ground Transportation Policy (Demo)",
        "category": "transportation",
        "destination": "global",
        "keywords": ["transport", "transportation", "transfer", "airport transfer",
                     "car rental", "public transport", "metro", "taxi", "rail",
                     "getting around", "airport", "get around", "travel card",
                     "transit pass", "drive", "driving"],
    },
    "safety": {
        "filename": "safety_policy.md",
        "policy_name": "Travel Safety Guidelines (Demo)",
        "category": "safety",
        "destination": "global",
        "keywords": ["safety", "safe", "security", "emergency", "health",
                     "vaccination", "advisory", "risk", "theft", "pickpocket"],
    },
    "booking-modification": {
        "filename": "booking_modification_policy.md",
        "policy_name": "Booking Modification Policy (Demo)",
        "category": "bookings",
        "destination": "global",
        "keywords": ["modify", "modification", "change my booking", "change booking",
                     "amend", "reschedule", "date change", "name change",
                     "change fee", "update booking"],
    },
}

# MCP resource URI scheme: travel://policies/<topic>
URI_PREFIX = "travel://policies"


def uri_for(topic: str) -> str:
    return f"{URI_PREFIX}/{topic}"


def metadata(topic: str) -> dict:
    spec = POLICIES[topic]
    return {
        "policy_name": spec["policy_name"],
        "category": spec["category"],
        "destination": spec["destination"],
        "version": VERSION,
        "effective_date": EFFECTIVE_DATE,
        "source": SOURCE,
        "uri": uri_for(topic),
        "topic": topic,
    }


def read_policy(topic: str) -> str:
    """Read a policy document's markdown text. Raises KeyError/FileNotFoundError."""
    spec = POLICIES[topic]
    path = POLICY_DOCS_DIR / spec["filename"]
    if not path.exists():
        raise FileNotFoundError(
            f"Policy file {spec['filename']} is missing. "
            "Run: uv run python -m scripts.generate_policies"
        )
    return path.read_text(encoding="utf-8")


def index() -> list[dict]:
    return [metadata(topic) for topic in POLICIES]


def find_policy(question: str, limit: int = 3) -> list[dict]:
    """Rank policy topics by keyword overlap with a natural-language question."""
    text = (question or "").lower()
    scored: list[tuple[int, str]] = []
    for topic, spec in POLICIES.items():
        score = 0
        for keyword in spec["keywords"]:
            if keyword in text:
                # Longer keyword matches are more specific -> weight higher.
                score += 2 if " " in keyword else 1
        # A bare "cancel" mention should surface both cancellation policies.
        if score == 0 and "cancel" in text and "cancellation" in topic:
            score = 1
        if score:
            scored.append((score, topic))

    scored.sort(reverse=True)
    return [{**metadata(topic), "match_score": score}
            for score, topic in scored[:limit]]
