"""Curated (but clearly demo) destination facts used to generate synthetic data.

Keeping the highlights curated — rather than random lorem — makes the RAG
knowledge base meaningful so semantic retrieval actually works in the demo.
All operational numbers (prices, seats, ratings) are synthetic/demo data.
"""
from __future__ import annotations

# destination city -> country + curated per-category highlights.
# Categories align with common/vectordb.CATEGORIES.
DESTINATIONS: dict[str, dict] = {
    "Tokyo": {
        "country": "Japan",
        "themes": ["food", "anime", "temples", "culture", "shopping", "technology"],
        "attractions": "Senso-ji temple in Asakusa, the Meiji Shrine, Shibuya Crossing, the teamLab digital art museums, and Tokyo Skytree for skyline views.",
        "food": "Sushi at Toyosu, ramen in Shinjuku, tempura, monjayaki, izakaya hopping, and conveyor-belt kaiten-zushi for budget dining.",
        "culture": "Anime and manga culture in Akihabara, sumo tournaments at Ryogoku, traditional tea ceremonies, and karaoke.",
        "transportation": "The metro and JR Yamanote line cover the city; a Suica/PASMO IC card and a Japan Rail Pass simplify travel.",
        "safety": "Very low crime; carry cash as many small shops are cash-only; be mindful of typhoon season in September.",
        "accommodation": "Options range from capsule hotels and business hotels to ryokan and luxury towers in Shinjuku and Ginza.",
        "activities": "Day trips to Nikko and Kamakura, a Mario-kart style street tour, and seasonal cherry-blossom or autumn-leaf viewing.",
        "weather": "October is mild and pleasant (15-22C) with autumn foliage; summers are hot and humid.",
        "local_customs": "Bow when greeting, remove shoes indoors, avoid tipping, keep quiet on trains, and don't eat while walking.",
    },
    "Kyoto": {
        "country": "Japan",
        "themes": ["temples", "culture", "food", "gardens", "history"],
        "attractions": "Fushimi Inari's torii gates, Kinkaku-ji (Golden Pavilion), Arashiyama bamboo grove, and Gion geisha district.",
        "food": "Kaiseki multi-course dining, yudofu (tofu hot pot), matcha sweets, and Nishiki Market street food.",
        "culture": "The best-preserved traditional culture in Japan: geisha, tea ceremony, Zen temples, and kimono rental experiences.",
        "transportation": "Buses are the main way around; a one-day bus pass is economical, supplemented by two subway lines.",
        "safety": "Extremely safe; respect photography rules in Gion where harassing geisha is prohibited.",
        "accommodation": "Traditional ryokan with tatami and onsen, machiya townhouse stays, and modern hotels near Kyoto Station.",
        "activities": "Temple hopping, a tea ceremony, a kimono walk in Higashiyama, and a bamboo-grove morning stroll.",
        "weather": "October brings crisp air and early autumn colours; peak foliage arrives in mid-to-late November.",
        "local_customs": "Reservation-only temples exist; be quiet and respectful in shrines and private gardens.",
    },
    "Osaka": {
        "country": "Japan",
        "themes": ["food", "nightlife", "culture", "family"],
        "attractions": "Osaka Castle, Dotonbori's neon canal, Universal Studios Japan, and the Umeda Sky Building.",
        "food": "Osaka is Japan's kitchen: takoyaki, okonomiyaki, kushikatsu, and street food along Dotonbori.",
        "culture": "Famously friendly, comedic locals; bunraku puppet theatre and a lively down-to-earth atmosphere.",
        "transportation": "An extensive subway network; the Osaka Amazing Pass bundles transit with attraction entry.",
        "safety": "Safe and welcoming; the usual care with belongings in crowded nightlife areas.",
        "accommodation": "Budget-friendly business hotels around Namba and Umeda, plus family options near Universal Studios.",
        "activities": "A food crawl in Dotonbori, a theme-park day, and a day trip to nearby Nara's deer park.",
        "weather": "October is comfortable and dry, a good time for walking food tours.",
        "local_customs": "Stand on the right of escalators (opposite to Tokyo); cash is widely used.",
    },
    "Paris": {
        "country": "France",
        "themes": ["museums", "food", "romance", "art", "history"],
        "attractions": "The Eiffel Tower, the Louvre, Notre-Dame, Montmartre and Sacre-Coeur, and the Musee d'Orsay.",
        "food": "Boulangerie croissants, bistro classics, cheese and wine, patisserie, and market picnics along the Seine.",
        "culture": "World-class art museums, fashion, cafe culture, and river-side book stalls (bouquinistes).",
        "transportation": "The Metro is dense and cheap; a Navigo or carnet of tickets covers most trips; the RER links the airports.",
        "safety": "Watch for pickpockets around major sights and on the Metro; keep bags zipped and close.",
        "accommodation": "Boutique hotels in Le Marais, mid-range options near the Latin Quarter, and luxury near the Champs-Elysees.",
        "activities": "A Seine river cruise, a day trip to Versailles, and evenings watching the Eiffel Tower sparkle.",
        "weather": "October is cool (8-16C) with occasional rain; pack layers and an umbrella.",
        "local_customs": "Greet shopkeepers with 'Bonjour', dining is leisurely, and tipping is modest as service is included.",
    },
    "Nice": {
        "country": "France",
        "themes": ["beach", "food", "relaxation", "art"],
        "attractions": "The Promenade des Anglais, Old Town (Vieux Nice), Castle Hill viewpoint, and the Matisse Museum.",
        "food": "Socca chickpea pancakes, salade nicoise, ratatouille, and fresh Mediterranean seafood.",
        "culture": "French Riviera art scene with Matisse and Chagall, plus a relaxed seaside pace.",
        "transportation": "A walkable centre with trams; regional trains reach Monaco, Cannes, and Antibes in minutes.",
        "safety": "Generally safe; typical beach-town care with valuables on the pebbled shore.",
        "accommodation": "Seafront hotels along the Promenade, and affordable stays in the Old Town.",
        "activities": "Beach days, coastal train hops to Monaco, and sunset drinks overlooking the bay.",
        "weather": "Mild Mediterranean climate; October remains pleasant for coastal walks.",
        "local_customs": "A relaxed Riviera etiquette; a friendly 'Bonjour' still goes a long way.",
    },
    "London": {
        "country": "United Kingdom",
        "themes": ["museums", "history", "theatre", "food", "shopping"],
        "attractions": "The British Museum, Tower of London, Westminster and Big Ben, the London Eye, and free national galleries.",
        "food": "Pub roasts, fish and chips, Borough Market, global street food, and a strong Indian curry scene.",
        "culture": "West End theatre, royal history, world-class (often free) museums, and diverse neighbourhoods.",
        "transportation": "The Underground and buses run on contactless tap-in; an Oyster or contactless card caps daily fares.",
        "safety": "Safe overall; mind pickpockets in tourist crowds and look right when crossing streets.",
        "accommodation": "Mid-range hotels in Kensington and Bloomsbury; budget chains and boutique stays across zones.",
        "activities": "A West End show, a Thames walk, day trips to Oxford or Windsor, and market browsing.",
        "weather": "October is cool and often wet (8-15C); an umbrella and layers are essential.",
        "local_customs": "Queue politely, stand on the right of escalators, and tipping is around 10-12.5% when not included.",
    },
    "Edinburgh": {
        "country": "United Kingdom",
        "themes": ["history", "culture", "nature", "festivals"],
        "attractions": "Edinburgh Castle, the Royal Mile, Arthur's Seat, and the Palace of Holyroodhouse.",
        "food": "Haggis, Scottish salmon, shortbread, and a growing whisky and gin bar scene.",
        "culture": "Literary heritage, the world-famous Fringe festival in August, and Gothic old-town charm.",
        "transportation": "A compact, walkable centre with trams and buses; the airport tram is convenient.",
        "safety": "Very safe; prepare for changeable weather when hiking Arthur's Seat.",
        "accommodation": "Historic hotels near the Royal Mile and cosy guesthouses in the New Town.",
        "activities": "A castle visit, a hike up Arthur's Seat, a whisky tasting, and ghost tours.",
        "weather": "Cool and windy; October is crisp with early sunsets, so pack warm layers.",
        "local_customs": "Friendly and informal; tipping around 10% is appreciated but not mandatory.",
    },
    "New York": {
        "country": "United States",
        "themes": ["museums", "food", "shopping", "nightlife", "art"],
        "attractions": "Central Park, the Statue of Liberty, the Met and MoMA, Times Square, and the High Line.",
        "food": "Bagels, pizza slices, deli sandwiches, global cuisine in every borough, and food halls.",
        "culture": "Broadway theatre, jazz clubs, world-class museums, and endlessly diverse neighbourhoods.",
        "transportation": "The 24/7 subway is the fastest way around; pay by contactless OMNY tap.",
        "safety": "Busy and generally safe in tourist areas; keep standard big-city awareness at night.",
        "accommodation": "Midtown mid-range hotels, boutique stays in SoHo, and budget options across the boroughs.",
        "activities": "A Broadway show, a Central Park stroll, a ferry past the Statue of Liberty, and museum days.",
        "weather": "October is crisp and pleasant (10-18C) with autumn colour in the parks.",
        "local_customs": "Tipping 18-20% is expected at restaurants; walk briskly and stand right on escalators.",
    },
    "San Francisco": {
        "country": "United States",
        "themes": ["nature", "technology", "food", "culture"],
        "attractions": "The Golden Gate Bridge, Alcatraz, Fisherman's Wharf, and cable cars over steep hills.",
        "food": "Sourdough bread bowls, Mission burritos, Dungeness crab, and a strong farm-to-table scene.",
        "culture": "Tech innovation, counterculture history in Haight-Ashbury, and vibrant Chinatown and Mission murals.",
        "transportation": "Cable cars, Muni, and BART; a Clipper card covers regional transit including to the airport.",
        "safety": "Take care with valuables; avoid leaving anything visible in parked cars.",
        "accommodation": "Union Square hotels, boutique stays near North Beach, and budget options in the outer districts.",
        "activities": "Biking the Golden Gate Bridge, an Alcatraz tour, and a day trip to Muir Woods or wine country.",
        "weather": "Mild but foggy; October is often the sunniest, warmest month, though evenings are cool.",
        "local_customs": "Tipping 18-20% is standard; layers are essential for the microclimates.",
    },
    "Rome": {
        "country": "Italy",
        "themes": ["history", "food", "art", "culture"],
        "attractions": "The Colosseum, Roman Forum, Vatican Museums and St. Peter's, the Pantheon, and Trevi Fountain.",
        "food": "Cacio e pepe, carbonara, Roman-style pizza, supplì, gelato, and espresso at the bar.",
        "culture": "Millennia of history layered across the city, Baroque squares, and a lively piazza life.",
        "transportation": "The historic centre is walkable; two metro lines and buses cover longer hops.",
        "safety": "Beware pickpockets on crowded buses and around major sites; keep bags in front.",
        "accommodation": "Charming hotels near the Pantheon and Trastevere; budget stays near Termini station.",
        "activities": "A skip-the-line Colosseum tour, a Vatican morning, and evening strolls through lit piazzas.",
        "weather": "October is warm and pleasant (12-22C), ideal for walking the ancient sites.",
        "local_customs": "Dress modestly for churches, cappuccino is a morning drink, and cover-charge (coperto) is normal.",
    },
    "Venice": {
        "country": "Italy",
        "themes": ["romance", "history", "art", "food"],
        "attractions": "St. Mark's Basilica and Square, the Grand Canal, the Rialto Bridge, and Murano and Burano islands.",
        "food": "Cicchetti bar snacks, fresh seafood risotto, squid-ink pasta, and spritz aperitivo.",
        "culture": "Venetian glassmaking, the Biennale art festival, gondola tradition, and Carnival masks.",
        "transportation": "There are no cars: walk or take vaporetto water buses along the canals.",
        "safety": "Very safe; watch your footing on bridges and beware acqua alta flooding in autumn.",
        "accommodation": "Canal-side boutique hotels; more affordable stays in Mestre on the mainland.",
        "activities": "A gondola ride, an island-hopping day to Murano and Burano, and getting lost in quiet backstreets.",
        "weather": "October is mild but can bring high-water flooding; pack waterproof shoes.",
        "local_customs": "Don't picnic on monuments; respect quiet residential canals and reservation-only spots.",
    },
    "Barcelona": {
        "country": "Spain",
        "themes": ["art", "beach", "food", "architecture", "nightlife"],
        "attractions": "Gaudi's Sagrada Familia and Park Guell, the Gothic Quarter, La Rambla, and city beaches.",
        "food": "Tapas, paella, jamon, seafood at La Boqueria market, and late-night dining.",
        "culture": "Catalan modernista architecture, a strong art scene, and vibrant festival calendar.",
        "transportation": "An easy metro network, plus a walkable old town; the T-casual card offers ten rides.",
        "safety": "Pickpocketing is common on La Rambla and the metro; stay alert in crowds.",
        "accommodation": "Design hotels in the Eixample, budget hostels in the Gothic Quarter, and beachside stays.",
        "activities": "A Gaudi architecture trail, a tapas crawl, a beach afternoon, and a day trip to Montserrat.",
        "weather": "October is warm and sunny (15-23C), still good for the beach midday.",
        "local_customs": "Dinner starts late (after 9pm); learn a few Catalan or Spanish greetings.",
    },
    "Madrid": {
        "country": "Spain",
        "themes": ["art", "food", "nightlife", "culture"],
        "attractions": "The Prado, Reina Sofia, Retiro Park, the Royal Palace, and Plaza Mayor.",
        "food": "Cocido stew, bocadillo de calamares, churros con chocolate, and a legendary tapas scene.",
        "culture": "The Golden Triangle of art museums, flamenco, and famously late nightlife.",
        "transportation": "A clean, extensive metro; the centre is very walkable.",
        "safety": "Safe overall; keep an eye on bags in busy plazas and on the metro.",
        "accommodation": "Central hotels near Sol and Gran Via; budget options in Lavapies.",
        "activities": "An art-museum day, a flamenco show, a Retiro Park picnic, and tapas hopping in La Latina.",
        "weather": "October is pleasant and dry (10-20C) with clear skies.",
        "local_customs": "Long lunches and late dinners; a siesta lull closes some shops mid-afternoon.",
    },
    "Singapore": {
        "country": "Singapore",
        "themes": ["food", "family", "shopping", "nature", "culture"],
        "attractions": "Gardens by the Bay, Marina Bay Sands, Sentosa, the Merlion, and Chinatown and Little India.",
        "food": "Hawker centres for Hainanese chicken rice, laksa, chilli crab, satay, and kaya toast.",
        "culture": "A multicultural blend of Chinese, Malay, Indian, and Peranakan heritage.",
        "transportation": "The clean, cheap MRT covers the island; an EZ-Link card makes it seamless.",
        "safety": "One of the safest cities globally; note strict laws on littering and jaywalking.",
        "accommodation": "Luxury towers at Marina Bay, mid-range hotels in Chinatown, and boutique shophouse stays.",
        "activities": "A Gardens by the Bay light show, a Sentosa beach day, and a hawker-centre food tour.",
        "weather": "Hot and humid year-round with afternoon showers; light clothing and an umbrella help.",
        "local_customs": "No chewing gum sales, no eating on the MRT, and tipping is not customary.",
    },
    "Bangkok": {
        "country": "Thailand",
        "themes": ["food", "temples", "nightlife", "shopping", "culture"],
        "attractions": "The Grand Palace and Wat Pho, Wat Arun, floating markets, and Chatuchak weekend market.",
        "food": "Pad thai, som tam, mango sticky rice, boat noodles, and street food everywhere.",
        "culture": "Ornate Buddhist temples, tuk-tuk chaos, and a warm 'Land of Smiles' hospitality.",
        "transportation": "The BTS Skytrain and MRT beat the traffic; river boats ply the Chao Phraya.",
        "safety": "Generally safe; use metered taxis or apps and be wary of gem-shop scams.",
        "accommodation": "Affordable luxury riverside hotels, mid-range stays near the BTS, and Khao San budget rooms.",
        "activities": "A temple circuit, a long-tail boat canal tour, a cooking class, and rooftop-bar evenings.",
        "weather": "Hot year-round; October is the tail of the rainy season with short heavy showers.",
        "local_customs": "Dress modestly at temples, never touch someone's head, and show respect for the monarchy.",
    },
    "Phuket": {
        "country": "Thailand",
        "themes": ["beach", "relaxation", "nightlife", "nature"],
        "attractions": "Patong and Kata beaches, the Big Buddha, Old Phuket Town, and Phang Nga Bay boat trips.",
        "food": "Fresh seafood, southern-Thai curries, night-market street food, and beach-side dining.",
        "culture": "Sino-Portuguese old town, island temples, and a laid-back beach lifestyle.",
        "transportation": "Songthaews and app taxis connect beaches; renting a scooter is common but risky.",
        "safety": "Respect strong monsoon-season currents and red-flag warnings on beaches.",
        "accommodation": "Beach resorts of every budget, from bungalows to luxury villas.",
        "activities": "Island-hopping to Phi Phi, snorkelling, a Big Buddha visit, and sunset viewpoints.",
        "weather": "October is shoulder season with occasional rain; the drier season starts in November.",
        "local_customs": "Cover up away from the beach and at temples; bargaining at markets is expected.",
    },
    "Sydney": {
        "country": "Australia",
        "themes": ["beach", "nature", "food", "family"],
        "attractions": "The Opera House, Harbour Bridge, Bondi Beach, the Royal Botanic Garden, and Darling Harbour.",
        "food": "Fresh seafood, brunch culture, multicultural eats, and the Sydney Fish Market.",
        "culture": "A relaxed outdoor lifestyle, harbour culture, and Aboriginal heritage sites.",
        "transportation": "Trains, ferries, and buses on a tap-and-go Opal card; ferries double as scenic rides.",
        "safety": "Very safe; swim between the flags and respect surf and sun conditions.",
        "accommodation": "Harbour-view hotels at The Rocks, mid-range in the CBD, and beachside stays at Bondi.",
        "activities": "The Bondi-to-Coogee coastal walk, an Opera House tour, a harbour ferry, and Blue Mountains day trips.",
        "weather": "October is spring: mild and pleasant (14-22C), warming toward summer.",
        "local_customs": "Casual and friendly; tipping is not expected but appreciated for great service.",
    },
    "Melbourne": {
        "country": "Australia",
        "themes": ["food", "art", "culture", "sport"],
        "attractions": "Federation Square, laneway street art, the Queen Victoria Market, and the MCG.",
        "food": "A world-class coffee scene, laneway cafes, diverse dining, and rooftop bars.",
        "culture": "Australia's cultural capital: galleries, live music, sport, and festivals.",
        "transportation": "Free tram zone in the CBD; a Myki card covers trams, trains, and buses.",
        "safety": "Safe and walkable; standard care at night in nightlife districts.",
        "accommodation": "Design hotels in the CBD, boutique stays in Fitzroy, and budget options near Southbank.",
        "activities": "A laneway coffee crawl, a Great Ocean Road day trip, and a sports or arts event.",
        "weather": "Famously changeable ('four seasons in a day'); spring October needs layers.",
        "local_customs": "Coffee culture is serious; casual dress is the norm.",
    },
    "Dubai": {
        "country": "UAE",
        "themes": ["luxury", "shopping", "family", "desert"],
        "attractions": "The Burj Khalifa, Dubai Mall and Fountain, Palm Jumeirah, and the old Al Fahidi district.",
        "food": "Emirati dishes, Middle Eastern mezze, global fine dining, and bustling souks.",
        "culture": "A fast-modern city blending Bedouin heritage with cutting-edge architecture.",
        "transportation": "A driverless metro and cheap taxis; the metro links the airport to downtown.",
        "safety": "Very safe with low crime; dress modestly and respect local laws and Ramadan customs.",
        "accommodation": "Iconic luxury resorts, mid-range hotels downtown, and value stays in Deira.",
        "activities": "A desert safari, the Burj Khalifa observation deck, dhow cruises, and souk shopping.",
        "weather": "October is warm and pleasant (24-35C) as summer heat eases; ideal for the desert.",
        "local_customs": "Modest dress in public, no public displays of affection, and reduced daytime dining in Ramadan.",
    },
    "Abu Dhabi": {
        "country": "UAE",
        "themes": ["luxury", "culture", "family"],
        "attractions": "The Sheikh Zayed Grand Mosque, Louvre Abu Dhabi, Yas Island, and the Corniche.",
        "food": "Emirati cuisine, Levantine mezze, and international dining on Saadiyat and Yas islands.",
        "culture": "The UAE's cultural heart with grand mosque architecture and museums.",
        "transportation": "Taxis are cheap and plentiful; buses cover the city and inter-emirate routes.",
        "safety": "Very safe; observe modest dress, especially at the Grand Mosque.",
        "accommodation": "Beach resorts on Saadiyat, family hotels near Yas Island, and downtown business hotels.",
        "activities": "A Grand Mosque visit, Louvre Abu Dhabi, Ferrari World, and a Corniche cycle.",
        "weather": "October is warm and dry, comfortable for sightseeing and the beach.",
        "local_customs": "Cover shoulders and knees at religious sites; women cover hair at the Grand Mosque.",
    },
    "Delhi": {
        "country": "India",
        "themes": ["history", "food", "culture", "shopping"],
        "attractions": "The Red Fort, Qutub Minar, Humayun's Tomb, India Gate, and the markets of Old Delhi.",
        "food": "Chaat, butter chicken, parathas, kebabs, and street food in Chandni Chowk.",
        "culture": "A layering of Mughal and colonial history alongside modern Indian life.",
        "transportation": "The clean, efficient Delhi Metro is the best way around; use app-based cabs otherwise.",
        "safety": "Take care with traffic and touts; women travellers should prefer registered transport at night.",
        "accommodation": "Heritage havelis, mid-range hotels in South Delhi, and budget stays in Paharganj.",
        "activities": "A Old Delhi food and rickshaw tour, monument visits, and a day trip to the Taj Mahal in Agra.",
        "weather": "October is pleasant post-monsoon (18-32C); winter mornings can be foggy.",
        "local_customs": "Remove shoes at temples, dress modestly, and bargaining is expected in markets.",
    },
    "Jaipur": {
        "country": "India",
        "themes": ["history", "culture", "shopping", "architecture"],
        "attractions": "Amber Fort, Hawa Mahal, City Palace, Jantar Mantar, and Nahargarh Fort views.",
        "food": "Dal baati churma, laal maas, ghewar sweets, and Rajasthani thali feasts.",
        "culture": "The 'Pink City' of Rajasthan, rich in royal heritage, crafts, and folk music.",
        "transportation": "Autos and app cabs are easiest; the compact old city is walkable.",
        "safety": "Generally safe for tourists; agree auto fares in advance and beware gem scams.",
        "accommodation": "Palace hotels, heritage havelis, and budget guesthouses near the old city.",
        "activities": "A fort and palace circuit, a block-printing workshop, and bazaar shopping for textiles.",
        "weather": "October is warm and dry, a comfortable time to visit after the monsoon.",
        "local_customs": "Dress modestly, remove shoes at temples, and haggle politely in the bazaars.",
    },
    "Mumbai": {
        "country": "India",
        "themes": ["food", "culture", "nightlife", "history"],
        "attractions": "The Gateway of India, Marine Drive, Elephanta Caves, and colonial-era architecture.",
        "food": "Vada pav, pav bhaji, seafood, Irani cafe fare, and street food at Chowpatty.",
        "culture": "India's film capital (Bollywood), a fast-paced financial hub with cosmopolitan energy.",
        "transportation": "Local trains are the city's lifeline; app cabs and autos fill the gaps.",
        "safety": "One of India's safer big cities; mind crowded trains and traffic.",
        "accommodation": "Sea-facing luxury hotels in Colaba, mid-range in Bandra, and budget stays near stations.",
        "activities": "A heritage walk in Fort, an Elephanta ferry, a street-food tour, and a Bollywood studio visit.",
        "weather": "October is humid post-monsoon; the pleasant, dry season begins in November.",
        "local_customs": "Dress modestly at religious sites; the city is liberal and welcoming otherwise.",
    },
}

# Airport hubs used as flight origins.
ORIGIN_HUBS = [
    "New York", "London", "Los Angeles", "San Francisco", "Chicago",
    "Toronto", "Dubai", "Singapore", "Sydney", "Delhi", "Frankfurt", "Paris",
]

AIRLINES = [
    "Demo Air", "SkyBridge Airlines", "Globe Wings", "AeroLink", "TransWorld Demo",
    "Pacific Blue Demo", "Continental Star", "Horizon Jet",
]

HOTEL_CATEGORIES = ["budget", "mid-range", "luxury"]

ACTIVITY_CATEGORY_BY_KNOWLEDGE = {
    "attractions": "sightseeing",
    "food": "food",
    "culture": "culture",
    "activities": "adventure",
    "accommodation": "leisure",
}
